# Generated by Django 3.1.7 on 2021-05-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stsnsapp', '0002_customuser_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='liquor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_many_liquor', models.IntegerField(default=1)),
            ],
        ),
    ]
