# Generated by Django 3.1.7 on 2021-05-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stsnsapp', '0004_auto_20210509_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquor',
            name='how_many_liquor',
            field=models.CharField(max_length=100),
        ),
    ]
