# Generated by Django 3.1.7 on 2021-05-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stsnsapp', '0005_auto_20210509_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquor',
            name='how_many_liquor',
            field=models.IntegerField(default=1),
        ),
    ]
