# Generated by Django 3.1.7 on 2021-05-11 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stsnsapp', '0006_auto_20210509_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='days',
            new_name='how_many_liquor',
        ),
        migrations.RenameField(
            model_name='liquor',
            old_name='how_many_liquor',
            new_name='how_many_liquor2',
        ),
    ]
