# Generated by Django 3.1.7 on 2021-05-15 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stsnsapp', '0008_liquor_user_liquor'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquor',
            name='how_many_cigalettes',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='cigalettes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_many_cigalettes', models.IntegerField(default=1)),
                ('user_liquor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
