# Generated by Django 3.1.7 on 2021-05-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stsnsapp', '0009_auto_20210515_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liquor',
            old_name='how_many_cigalettes',
            new_name='how_many_cigalettes2',
        ),
        migrations.AddField(
            model_name='customuser',
            name='how_many_cigalettes',
            field=models.IntegerField(default=1),
        ),
    ]
