# Generated by Django 3.1.7 on 2021-05-16 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stsnsapp', '0010_auto_20210516_0102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cigalettes',
            old_name='user_liquor',
            new_name='user_cigalettes',
        ),
        migrations.RemoveField(
            model_name='liquor',
            name='how_many_cigalettes2',
        ),
    ]
