# Generated by Django 3.1.7 on 2021-05-16 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stsnsapp', '0011_auto_20210516_0239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cigalettes',
            old_name='how_many_cigalettes',
            new_name='how_many_cigalettes2',
        ),
    ]
