# Generated by Django 3.1.7 on 2021-05-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stsnsapp', '0012_auto_20210516_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cigalettes',
            name='how_many_cigalettes2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='liquor',
            name='how_many_liquor2',
            field=models.IntegerField(default=0),
        ),
    ]
