# Generated by Django 3.1.7 on 2021-05-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stsnsapp', '0014_boardmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='good',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
