# Generated by Django 3.1.7 on 2021-05-24 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stsnsapp', '0016_auto_20210524_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardmodel',
            name='image',
        ),
    ]
