# Generated by Django 3.1.7 on 2021-05-25 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stsnsapp', '0017_remove_boardmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='user_Board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='liquor',
            name='user_liquor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
