# Generated by Django 3.1.7 on 2021-05-25 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stsnsapp', '0018_auto_20210525_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardmodel',
            name='user_Board',
        ),
        migrations.AlterField(
            model_name='boardmodel',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
