# Generated by Django 3.1.7 on 2021-05-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stsnsapp', '0019_auto_20210525_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='boardmodel',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
