# Generated by Django 3.1.7 on 2021-05-30 12:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stsnsapp', '0021_auto_20210525_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
